# SPDX-License-Identifier: AGPL-3.0-or-later
[package]
name = "nickel-ffi-shim"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
nickel-lang-core = "0.10"

[profile.release]
lto = true
